import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedChevronleftWidget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedHotelListWidget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedBEACHWidget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedCoxsBazarWidget.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/bookapp/generatedcategoryfilterwidget/generated/GeneratedLogo_bed_Icon1Widget.dart';

/* Frame Category Filter
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCategoryFilterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 896.0,
                      child: GeneratedRectangle22Widget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 549.0,
                      child: GeneratedRectangle23Widget1(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 125.0,
                      right: null,
                      bottom: null,
                      width: 121.0,
                      height: 50.0,
                      child: GeneratedBEACHWidget(),
                    ),
                    Positioned(
                      left: 31.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 207.0,
                      height: 47.0,
                      child: GeneratedCoxsBazarWidget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 62.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedRectangle14Widget1(),
                    ),
                    Positioned(
                      left: 34.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedChevronleftWidget(),
                    ),
                    Positioned(
                      left: 169.0,
                      top: 369.0,
                      right: null,
                      bottom: null,
                      width: 79.0,
                      height: 25.0,
                      child: GeneratedHotelListWidget(),
                    ),
                    Positioned(
                      left: 172.0,
                      top: 312.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 70.0,
                      child: GeneratedEllipse1Widget(),
                    ),
                    Positioned(
                      left: 186.0,
                      top: 319.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedLogo_bed_Icon1Widget(),
                    ),
                    Positioned(
                      left: 76.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 263.0,
                      height: 0.5,
                      child: GeneratedLine4Widget(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 492.0,
                      child: GeneratedFrame3Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 61.0,
              child: GeneratedGroup2Widget1(),
            )
          ]),
    ));
  }
}
