import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedSearchWidget7.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedGroup9Widget2.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/Generated02Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedEXPLOREWidget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedArrowdownWidget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/Generated01042020Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedHiWidget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedPLANATRIPWidget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedArWidget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedWhereareyouthinkingofgoingWidget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedCoxsBazarChittagongWidget3.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedKolkataIndiaWidget.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedAdultWidget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/Generated01Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedDpWidget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/Generated01062020Widget1.dart';
import 'package:flutterapp/bookapp/generatedhomewidget4/generated/GeneratedBabyWidget1.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1023.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1023.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 245, 255, 254),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 164.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 120.0,
                                    child: GeneratedFrame1Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 322.0,
                                    right: null,
                                    bottom: null,
                                    width: 111.0,
                                    height: 35.0,
                                    child: GeneratedEXPLOREWidget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 576.0,
                                    right: null,
                                    bottom: null,
                                    width: 145.0,
                                    height: 32.0,
                                    child: GeneratedPLANATRIPWidget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 364.0,
                                    right: null,
                                    bottom: null,
                                    width: 385.0,
                                    height: 171.0,
                                    child: GeneratedFrame2Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 618.0,
                                    right: null,
                                    bottom: null,
                                    width: 354.0,
                                    height: 101.0,
                                    child: GeneratedRectangle13Widget1(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 731.0,
                                    right: null,
                                    bottom: null,
                                    width: 354.0,
                                    height: 51.0,
                                    child: GeneratedRectangle15Widget1(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 877.0,
                                    right: null,
                                    bottom: null,
                                    width: 354.0,
                                    height: 51.0,
                                    child: GeneratedRectangle18Widget1(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 804.0,
                                    right: null,
                                    bottom: null,
                                    width: 165.0,
                                    height: 51.0,
                                    child: GeneratedRectangle16Widget1(),
                                  ),
                                  Positioned(
                                    left: 219.0,
                                    top: 804.0,
                                    right: null,
                                    bottom: null,
                                    width: 165.0,
                                    height: 51.0,
                                    child: GeneratedRectangle17Widget1(),
                                  ),
                                  Positioned(
                                    left: 57.0,
                                    top: 634.0,
                                    right: null,
                                    bottom: null,
                                    width: 116.0,
                                    height: 25.0,
                                    child: GeneratedKolkataIndiaWidget(),
                                  ),
                                  Positioned(
                                    left: 57.0,
                                    top: 681.0,
                                    right: null,
                                    bottom: null,
                                    width: 200.0,
                                    height: 25.0,
                                    child:
                                        GeneratedCoxsBazarChittagongWidget3(),
                                  ),
                                  Positioned(
                                    left: 97.0,
                                    top: 745.0,
                                    right: null,
                                    bottom: null,
                                    width: 104.0,
                                    height: 28.0,
                                    child: Generated01042020Widget1(),
                                  ),
                                  Positioned(
                                    left: 129.0,
                                    top: 819.0,
                                    right: null,
                                    bottom: null,
                                    width: 26.0,
                                    height: 28.0,
                                    child: Generated02Widget1(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 819.0,
                                    right: null,
                                    bottom: null,
                                    width: 22.0,
                                    height: 28.0,
                                    child: Generated01Widget1(),
                                  ),
                                  Positioned(
                                    left: 260.0,
                                    top: 745.0,
                                    right: null,
                                    bottom: null,
                                    width: 103.0,
                                    height: 28.0,
                                    child: Generated01062020Widget1(),
                                  ),
                                  Positioned(
                                    left: 57.0,
                                    top: 745.0,
                                    right: null,
                                    bottom: null,
                                    width: 33.0,
                                    height: 28.0,
                                    child: GeneratedDpWidget1(),
                                  ),
                                  Positioned(
                                    left: 57.0,
                                    top: 818.0,
                                    right: null,
                                    bottom: null,
                                    width: 49.0,
                                    height: 28.0,
                                    child: GeneratedAdultWidget1(),
                                  ),
                                  Positioned(
                                    left: 246.0,
                                    top: 818.0,
                                    right: null,
                                    bottom: null,
                                    width: 49.0,
                                    height: 28.0,
                                    child: GeneratedBabyWidget1(),
                                  ),
                                  Positioned(
                                    left: 220.0,
                                    top: 745.0,
                                    right: null,
                                    bottom: null,
                                    width: 25.0,
                                    height: 28.0,
                                    child: GeneratedArWidget1(),
                                  ),
                                  Positioned(
                                    left: 57.0,
                                    top: 669.0,
                                    right: null,
                                    bottom: null,
                                    width: 232.0,
                                    height: 0.5,
                                    child: GeneratedLine1Widget1(),
                                  ),
                                  Positioned(
                                    left: 207.0,
                                    top: 741.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 1.0,
                                    child: GeneratedLine2Widget1(),
                                  ),
                                  Positioned(
                                    left: 324.0,
                                    top: 657.0,
                                    right: null,
                                    bottom: null,
                                    width: 24.0,
                                    height: 24.0,
                                    child: GeneratedArrowdownWidget1(),
                                  ),
                                  Positioned(
                                    left: 318.0,
                                    top: 651.0,
                                    right: null,
                                    bottom: null,
                                    width: 35.0,
                                    height: 35.0,
                                    child: GeneratedRectangle14Widget4(),
                                  ),
                                  Positioned(
                                    left: 177.0,
                                    top: 891.0,
                                    right: null,
                                    bottom: null,
                                    width: 65.0,
                                    height: 28.0,
                                    child: GeneratedSearchWidget7(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 71.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 47.0,
                                    child: GeneratedHiWidget(),
                                  ),
                                  Positioned(
                                    left: 32.0,
                                    top: 116.0,
                                    right: null,
                                    bottom: null,
                                    width: 223.0,
                                    height: 20.0,
                                    child:
                                        GeneratedWhereareyouthinkingofgoingWidget(),
                                  ),
                                  Positioned(
                                    left: 313.0,
                                    top: 74.0,
                                    right: null,
                                    bottom: null,
                                    width: 60.0,
                                    height: 60.0,
                                    child: GeneratedGroup9Widget2(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 61.0,
              child: GeneratedGroup3Widget(),
            )
          ]),
    ));
  }
}
