import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedandroidlarge6widget/generated/GeneratedGroup14Widget.dart';

/* Frame Android Large - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedGroup14Widget(),
              )
            ]),
      ),
    ));
  }
}
