import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedChevronleftWidget2.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedHotelListWidget2.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedFrame3Widget3.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedGroup2Widget3.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedLogo_bed_Icon1Widget2.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedMYPROFILEWidget.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedRectangle23Widget5.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedLine4Widget2.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedRectangle22Widget5.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/bookapp/generateduserwidget3/generated/GeneratedRectangle14Widget3.dart';

/* Frame User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 896.0,
                      child: GeneratedRectangle22Widget5(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 549.0,
                      child: GeneratedRectangle23Widget5(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 125.0,
                      right: null,
                      bottom: null,
                      width: 208.0,
                      height: 47.0,
                      child: GeneratedMYPROFILEWidget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 62.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedRectangle14Widget3(),
                    ),
                    Positioned(
                      left: 34.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedChevronleftWidget2(),
                    ),
                    Positioned(
                      left: 169.0,
                      top: 369.0,
                      right: null,
                      bottom: null,
                      width: 79.0,
                      height: 25.0,
                      child: GeneratedHotelListWidget2(),
                    ),
                    Positioned(
                      left: 172.0,
                      top: 312.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 70.0,
                      child: GeneratedEllipse1Widget2(),
                    ),
                    Positioned(
                      left: 186.0,
                      top: 319.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedLogo_bed_Icon1Widget2(),
                    ),
                    Positioned(
                      left: 76.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 263.0,
                      height: 0.5,
                      child: GeneratedLine4Widget2(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 492.0,
                      child: GeneratedFrame3Widget3(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 560.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 0.5,
                      child: GeneratedLine5Widget1(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 656.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 0.5,
                      child: GeneratedLine6Widget(),
                    ),
                    Positioned(
                      left: 17.0,
                      top: 446.0,
                      right: null,
                      bottom: null,
                      width: 60.0,
                      height: 60.0,
                      child: GeneratedGroup9Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 61.0,
              child: GeneratedGroup2Widget3(),
            )
          ]),
    ));
  }
}
