import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedLetsExploreforyournexttripWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedPhoneemailorusernameWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedSigninWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedLoginwithaccountWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle28Widget1.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedDonthaveanaccountRegisterWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedEyeoffWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedFacebookWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedLogo021Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedArcticonsgoogleWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/bookapp/generatedloginpagewidget/generated/GeneratedRectangle29Widget2.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.5024154589371981;
                  double scaleX = (constraints.maxWidth * percentWidth) / 208.0;

                  double percentHeight = 0.23214285714285715;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 208.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5410628019323671,
                        translateY:
                            constraints.maxHeight * 0.025669642857142856,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse2Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8429951690821256;
                  double scaleX = (constraints.maxWidth * percentWidth) / 349.0;

                  double percentHeight = 0.38950892857142855;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 349.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * -0.21497584541062803,
                        translateY: constraints.maxHeight * 0.6897321428571429,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse3Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 414.0;

                  double percentHeight = 1.0;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 896.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle27Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.391304347826087;

                  final double height =
                      constraints.maxHeight * 0.10379464285714286;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.30434782608695654,
                        y: constraints.maxHeight * 0.11830357142857142,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLogo021Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4178743961352657;

                  final double height =
                      constraints.maxHeight * 0.05580357142857143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07246376811594203,
                        y: constraints.maxHeight * 0.30245535714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWelcomeWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5869565217391305;

                  final double height =
                      constraints.maxHeight * 0.06919642857142858;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07246376811594203,
                        y: constraints.maxHeight * 0.35267857142857145,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLetsExploreforyournexttripWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.855072463768116;

                  final double height =
                      constraints.maxHeight * 0.06696428571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07246376811594203,
                        y: constraints.maxHeight * 0.4720982142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle16Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.855072463768116;

                  final double height =
                      constraints.maxHeight * 0.06696428571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07246376811594203,
                        y: constraints.maxHeight * 0.5558035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle28Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6859903381642513;

                  final double height =
                      constraints.maxHeight * 0.06696428571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17391304347826086,
                        y: constraints.maxHeight * 0.8515625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle29Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1932367149758454;

                  final double height =
                      constraints.maxHeight * 0.05357142857142857;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2463768115942029,
                        y: constraints.maxHeight * 0.71875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle30Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.1932367149758454;

                  final double height =
                      constraints.maxHeight * 0.05357142857142857;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5603864734299517,
                        y: constraints.maxHeight * 0.71875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle31Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5289855072463768;

                  final double height =
                      constraints.maxHeight * 0.027901785714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13285024154589373,
                        y: constraints.maxHeight * 0.4921875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPhoneemailorusernameWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.38405797101449274;

                  final double height =
                      constraints.maxHeight * 0.027901785714285716;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07246376811594203,
                        y: constraints.maxHeight * 0.6763392857142857,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLoginwithaccountWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.20531400966183574;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.13285024154589373,
                        y: constraints.maxHeight * 0.5758928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPasswordWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.057971014492753624;

                  final double height =
                      constraints.maxHeight * 0.026785714285714284;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8309178743961353,
                        y: constraints.maxHeight * 0.5758928571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEyeoffWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18115942028985507;

                  final double height =
                      constraints.maxHeight * 0.03571428571428571;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.427536231884058,
                        y: constraints.maxHeight * 0.8683035714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSigninWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.37681159420289856;

                  final double height =
                      constraints.maxHeight * 0.016741071428571428;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3140096618357488,
                        y: constraints.maxHeight * 0.9330357142857143,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDonthaveanaccountRegisterWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 260.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArcticonsgoogleWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.057971014492753624;

                  final double height =
                      constraints.maxHeight * 0.026785714285714284;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.3140096618357488,
                        y: constraints.maxHeight * 0.7321428571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFacebookWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
