import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedArWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedSetYourParameterWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedDpWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/Generated02Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedBabyWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/Generated01042020Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/Generated01Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/Generated01062020Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedArrowdownWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedDhakaDhakaWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedAdultWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedCoxsBazarChittagongWidget.dart';
import 'package:flutterapp/bookapp/generatedhover_1widget/generated/GeneratedRectangle13Widget.dart';

/* Frame hover_1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHover_1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 395.0,
        height: 391.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 32.0,
                child: GeneratedSetYourParameterWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 101.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 51.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 51.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 51.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 208.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 51.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 25.0,
                child: GeneratedDhakaDhakaWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 25.0,
                child: GeneratedCoxsBazarChittagongWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 28.0,
                child: Generated01042020Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 28.0,
                child: Generated02Widget(),
              ),
              Positioned(
                left: 307.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 28.0,
                child: Generated01Widget(),
              ),
              Positioned(
                left: 249.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 28.0,
                child: Generated01062020Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 28.0,
                child: GeneratedDpWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 28.0,
                child: GeneratedAdultWidget(),
              ),
              Positioned(
                left: 235.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 28.0,
                child: GeneratedBabyWidget(),
              ),
              Positioned(
                left: 209.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 28.0,
                child: GeneratedArWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 232.0,
                height: 0.5,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 313.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowdownWidget(),
              ),
              Positioned(
                left: 307.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 166.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 28.0,
                child: GeneratedSearchWidget(),
              )
            ]),
      ),
    ));
  }
}
