import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnterasMMYYWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedPaymentWidget2.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedFontistoamericanexpressWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnterCodeFIRSTTIMEWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedTablerdiscount2Widget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedPaymentWidget3.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine2Widget3.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedFluentpayment20filledWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedClaritysuccesslineWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedCardNumberWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine4Widget3.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedApplyWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedToavail10offWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedInfoWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedCVVWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnteraDiscountCodeWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedBiinfocirclefillWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedExpirationWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLogosvisaWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnterYourNameWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedCreditDebitCardWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedRectangle13Widget3.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine9Widget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnterCodeifanyWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedRectangle12Widget5.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedConfirmPaymentWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedSuccessWidget1.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedBrandicodiscoverWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedLogosmastercardWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedEnterCVVWidget.dart';
import 'package:flutterapp/bookapp/generatedpaymentwidget1/generated/GeneratedBxarrowbackWidget1.dart';

/* Frame Payment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 147.0,
                child: GeneratedRectangle12Widget5(),
              ),
              Positioned(
                left: 74.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 62.0,
                child: GeneratedPaymentWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 56.0,
                child: GeneratedBxarrowbackWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedBiinfocirclefillWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 40.0,
                child: GeneratedInfoWidget1(),
              ),
              Positioned(
                left: 160.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 40.0,
                child: GeneratedPaymentWidget3(),
              ),
              Positioned(
                left: 300.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 40.0,
                child: GeneratedSuccessWidget1(),
              ),
              Positioned(
                left: 178.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 56.0,
                child: GeneratedFluentpayment20filledWidget1(),
              ),
              Positioned(
                left: 327.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 40.0,
                child: GeneratedClaritysuccesslineWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 38.0,
                child: GeneratedCardNumberWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 1.0,
                child: GeneratedLine2Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 48.0,
                child: GeneratedEnterYourNameWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 38.0,
                child: GeneratedEnterCodeifanyWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 1.0,
                child: GeneratedLine5Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 48.0,
                child: GeneratedEnteraDiscountCodeWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 41.0,
                child: GeneratedCVVWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 48.0,
                child: GeneratedEnterCVVWidget(),
              ),
              Positioned(
                left: 171.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 41.0,
                child: GeneratedExpirationWidget(),
              ),
              Positioned(
                left: 171.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 1.0,
                child: GeneratedLine4Widget3(),
              ),
              Positioned(
                left: 171.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 48.0,
                child: GeneratedEnterasMMYYWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 394.0,
                height: 81.0,
                child: GeneratedRectangle14Widget5(),
              ),
              Positioned(
                left: 10.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 81.0,
                child: GeneratedCreditDebitCardWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 80.0,
                child: GeneratedRectangle13Widget3(),
              ),
              Positioned(
                left: 39.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 80.0,
                child: GeneratedConfirmPaymentWidget(),
              ),
              Positioned(
                left: 348.0,
                top: 840.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 56.0,
                child: GeneratedBrandicodiscoverWidget(),
              ),
              Positioned(
                left: 233.0,
                top: 855.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 28.0,
                child: GeneratedFontistoamericanexpressWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 850.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 28.0,
                child: GeneratedLogosmastercardWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 851.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 28.0,
                child: GeneratedLogosvisaWidget(),
              ),
              Positioned(
                left: 333.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 53.0,
                child: GeneratedApplyWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 71.0,
                child: GeneratedTablerdiscount2Widget(),
              ),
              Positioned(
                left: 101.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 33.0,
                child: GeneratedEnterCodeFIRSTTIMEWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 36.0,
                child: GeneratedToavail10offWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 1.0,
                child: GeneratedLine9Widget(),
              )
            ]),
      ),
    ));
  }
}
