import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedsearchwidget1/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/bookapp/generatedsearchwidget1/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/bookapp/generatedsearchwidget1/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/bookapp/generatedsearchwidget1/generated/GeneratedGroup2Widget.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1161.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 414.0,
                            height: 1023.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: null,
                                    top: 143.0,
                                    right: null,
                                    bottom: null,
                                    width: 354.0,
                                    height: 172.0,
                                    child: GeneratedGroup10Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 315.0,
                                    right: null,
                                    bottom: null,
                                    width: 414.0,
                                    height: 846.0,
                                    child: GeneratedFrame3Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 30.0,
              top: 68.0,
              right: null,
              bottom: null,
              width: 354.0,
              height: 60.0,
              child: GeneratedGroup11Widget(),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 61.0,
              child: GeneratedGroup2Widget(),
            )
          ]),
    ));
  }
}
