import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedAntdesignstarfilledWidget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedCoxsBazarBangladeshWidget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedLocatedinKolkataRaajkutirisconnectedtoashoppingcentreHo.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedAntdesignstarfilledWidget2.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedRectangle11Widget4.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedBxsstarhalfWidget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/Generated45Widget7.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedAntdesignstarfilledWidget3.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedBDT4500nightWidget.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedAntdesignstarfilledWidget1.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedRaajkutirWidget1.dart';
import 'package:flutterapp/bookapp/generatedinformationwidget/generated/GeneratedBOOKNOWWidget.dart';

/* Frame Information
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInformationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 313.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 609.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 29.0,
                child: GeneratedCoxsBazarBangladeshWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 92.0,
                child: GeneratedRaajkutirWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 40.0,
                child: GeneratedAntdesignstarfilledWidget(),
              ),
              Positioned(
                left: 150.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 40.0,
                child: GeneratedAntdesignstarfilledWidget1(),
              ),
              Positioned(
                left: 62.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 40.0,
                child: GeneratedAntdesignstarfilledWidget2(),
              ),
              Positioned(
                left: 106.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 40.0,
                child: GeneratedAntdesignstarfilledWidget3(),
              ),
              Positioned(
                left: 193.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 40.0,
                child: GeneratedBxsstarhalfWidget(),
              ),
              Positioned(
                left: 250.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 29.0,
                child: Generated45Widget7(),
              ),
              Positioned(
                left: 18.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 358.0,
                child:
                    GeneratedLocatedinKolkataRaajkutirisconnectedtoashoppingcentreHo(),
              ),
              Positioned(
                left: 18.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 57.0,
                child: GeneratedRectangle11Widget4(),
              ),
              Positioned(
                left: 22.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 59.0,
                child: GeneratedBDT4500nightWidget(),
              ),
              Positioned(
                left: 231.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 57.0,
                child: GeneratedRectangle10Widget3(),
              ),
              Positioned(
                left: 231.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 59.0,
                child: GeneratedBOOKNOWWidget(),
              )
            ]),
      ),
    ));
  }
}
