import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedFrame3Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedRectangle22Widget3.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedLogo_bed_Icon1Widget1.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedHotelListWidget1.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedBOOKMARKSWidget.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/bookapp/generatedbookmarkswidget/generated/GeneratedChevronleftWidget1.dart';

/* Frame Bookmarks
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookmarksWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 896.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 896.0,
                      child: GeneratedRectangle22Widget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 347.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 549.0,
                      child: GeneratedRectangle23Widget3(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 125.0,
                      right: null,
                      bottom: null,
                      width: 229.0,
                      height: 50.0,
                      child: GeneratedBOOKMARKSWidget(),
                    ),
                    Positioned(
                      left: 30.0,
                      top: 62.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedRectangle14Widget2(),
                    ),
                    Positioned(
                      left: 34.0,
                      top: 67.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedChevronleftWidget1(),
                    ),
                    Positioned(
                      left: 169.0,
                      top: 369.0,
                      right: null,
                      bottom: null,
                      width: 79.0,
                      height: 25.0,
                      child: GeneratedHotelListWidget1(),
                    ),
                    Positioned(
                      left: 172.0,
                      top: 312.0,
                      right: null,
                      bottom: null,
                      width: 70.0,
                      height: 70.0,
                      child: GeneratedEllipse1Widget1(),
                    ),
                    Positioned(
                      left: 186.0,
                      top: 319.0,
                      right: null,
                      bottom: null,
                      width: 35.0,
                      height: 35.0,
                      child: GeneratedLogo_bed_Icon1Widget1(),
                    ),
                    Positioned(
                      left: 76.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 263.0,
                      height: 0.5,
                      child: GeneratedLine4Widget1(),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 404.0,
                      right: null,
                      bottom: null,
                      width: 414.0,
                      height: 492.0,
                      child: GeneratedFrame3Widget2(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 414.0,
              height: 61.0,
              child: GeneratedGroup2Widget2(),
            )
          ]),
    ));
  }
}
