import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedandroidlarge4widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/bookapp/generatedandroidlarge4widget/generated/GeneratedPlanyournextvacationaffordablyWidget.dart';
import 'package:flutterapp/bookapp/generatedandroidlarge4widget/generated/GeneratedFlatcoloriconsnextWidget.dart';

/* Frame Android Large - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 896.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 350.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedFlatcoloriconsnextWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 218.0,
                child: GeneratedPlanyournextvacationaffordablyWidget(),
              )
            ]),
      ),
    ));
  }
}
