import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedNumberOfGuestsWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedFluentpayment20filledWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEmalAddresssWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEnterTotalNumberofGuestsWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedBookingInfoWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedSuccessWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEnterYourEmailWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedLine2Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedFullNameWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedPayNowWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedNumberofNightsWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedPaymentWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEnterYourNameWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEnterTheDurationOfStayWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedBxarrowbackWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedEnterPhoneNumberWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedRectangle12Widget4.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedBiinfocirclefillWidget.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/bookapp/generatedbookingwidget/generated/GeneratedClaritysuccesslineWidget.dart';

/* Frame Booking
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 151.0,
                child: GeneratedRectangle12Widget4(),
              ),
              Positioned(
                left: 74.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 63.0,
                child: GeneratedBookingInfoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 57.0,
                child: GeneratedBxarrowbackWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 37.0,
                child: GeneratedBiinfocirclefillWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 41.0,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 160.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 41.0,
                child: GeneratedPaymentWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 41.0,
                child: GeneratedSuccessWidget(),
              ),
              Positioned(
                left: 178.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 58.0,
                child: GeneratedFluentpayment20filledWidget(),
              ),
              Positioned(
                left: 327.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 42.0,
                child: GeneratedClaritysuccesslineWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 39.0,
                child: GeneratedFullNameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 1.0,
                child: GeneratedLine2Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 50.0,
                child: GeneratedEnterYourNameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 657.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 39.0,
                child: GeneratedNumberofNightsWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 703.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 50.0,
                child: GeneratedEnterTheDurationOfStayWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 39.0,
                child: GeneratedNumberOfGuestsWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 50.0,
                child: GeneratedEnterTotalNumberofGuestsWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 39.0,
                child: GeneratedEmalAddresssWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 1.0,
                child: GeneratedLine5Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 49.0,
                child: GeneratedEnterYourEmailWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 39.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 49.0,
                child: GeneratedEnterPhoneNumberWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 82.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 46.0,
                top: 816.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 82.0,
                child: GeneratedPayNowWidget(),
              )
            ]),
      ),
    ));
  }
}
