import 'package:flutter/material.dart';
import 'package:flutterapp/bookapp/generatedandroidlarge2widget/generated/GeneratedTransitionwipeWidget.dart';

/* Frame Android Large - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedAndroidLarge1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -210.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 834.0,
                  height: 896.0,
                  child: GeneratedTransitionwipeWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
